name: CI

on:
  push:
    branches: [master, v2]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        haxe-version:
          - stable
        target:
          - node

    steps:
      - uses: actions/checkout@v2

      - run: echo "::set-output name=dir::$(yarn cache dir)"
        id: yarn-cache-dir-path

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: actions/cache@v1
        with:
          path: ~/haxe
          key: ${{ runner.os }}-haxe-${{ hashFiles('haxe_libraries/*') }}

      - uses: lix-pm/setup-lix@master
      - run: lix install haxe ${{ matrix.haxe-version }}
      - run: lix download
      - run: lix run travix ${{ matrix.target }}
        env:
          CI: true
